org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true

kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true

GROUP=dev.befrvnk.composetty
POM_ARTIFACT_ID=ghostty-compose
VERSION_NAME=0.1.0-SNAPSHOT

POM_NAME=Composetty
POM_DESCRIPTION=A Compose Multiplatform terminal component powered by libghostty.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/befrvnk/composetty
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/befrvnk/composetty
POM_SCM_CONNECTION=scm:git:git://github.com/befrvnk/composetty.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/befrvnk/composetty.git
